canonical/mir-ci

- frame/display_server.py
- frame/helpers.py
- frame/program.py
- frame/readme.md
- frame/test_apps_can_run.py
- frame/test_tests.py
This prints a nicely formatted log for each program run (even if the program exits successfully). Pretty formatting was borrowed from [gtk layer shell](https://github.com/wmww/gtk-layer-shell/blob/124ccc2772d5ecbb40b54872c22e594c74bd39bc/test/run-integration-test.py#L60). I also switched the recommended way of running tests to pytest, as that only shows the stdout of tests that fail. `python3 -m unittest` still works, but prints out all logs for all tests even if they pass.
> Show more logs and switch to pytest

- bin/process_snaps.py
Snaps with 20/, 22/ tracks:
- ubuntu-frame
- ubuntu-frame-osk
- ubuntu-frame-vnc
- mir-test-tools
- graphics-test-tools
Snaps moving over to 22.04:
- confined-shell
Snaps remaining on 20.04:
- mir-kiosk
- mir-kiosk-kodi
- mir-kiosk-scummvm
- mir-kiosk-neverputt
- mir-kiosk-x11
- egmde
- mircade
> snaps: refresh snap lists

- frame/program.py
- frame/test_apps_can_run.py
As mentioned in the sync the integration tests fail if multiple runs hit the gedit test at the same time or gedit is already running on the system. The `-s` flag prevents gedit from combing multiple launches into a single process and fixes the problem.
> Prevent gedit from consolidating multiple instances

- frame/requirements.txt
- frame/test_apps_can_run.py
- frame/test_screencopy_bandwidth.py
- frame/test_server.py
- frame/test_tests.py
Pytest's `record_property()` feature (which will be used in a subsequent PR) isn't compatible with `parameterized`. Since pytest has it's own perfectly serviceable peramaterization, we might as well drop parameterized.
Also with pytest inheriting from `TestCase` is not necessary, and doing so breaks pytest peramaterization.
> Use pytest for test peramaterization

- .github/workflows/test.yml
- .gitignore
- frame/data/wayland.xml
- frame/data/wlr-screencopy-unstable-v1.xml
- frame/display_server.py
- frame/program.py
- frame/protocols/.gitignore
- frame/protocols/__init__.py
- frame/readme.md
- frame/requirements.txt
- frame/screencopy_tracker.py
- frame/test_screencopy_bandwidth.py
- frame/wayland_client.py
Based on #10. Adds a python-based tool that measures how many pixels are pushed over the screencopy protocol. Screencopy bandwidth tests are updated to record it's output as junit properties.
> Add screencopy measurement tool

- frame/screencopy_tracker.py
- frame/wayland_client.py
I haven't seen any deadlocks with the existing code, but I have seen them with new code I'm writing and I think they're possible with existing code. My theory as to what's going on is `display.roundtrip()` dispatches, we have our own dispatch thread, and things go poorly when there are multiple dispatcher. Implementing roundtrip ourselves such that it uses our dispatcher fixes this problem.
> Implement roundtrip to avoid deadlocks

- frame/pytest.ini
Without this we get the warning:
```
PytestWarning: record_property is incompatible with junit_family 'xunit2' (use 'legacy' or 'xunit1')
```
> Add pytest.ini to stop junit_family warning

- frame/test_server.py
Test wasn't getting run because of name
> Fix name of smoke tests class

- frame/pytest.ini
- frame/requirements.txt
- frame/screencopy_tracker.py
- frame/test_screencopy_bandwidth.py
- frame/wayland_client.py
What we were doing before was wildly unsafe, and I think may have been introducing some random failures (especially with the virtual pointer tests I've been working on)
> Switch from threading to asyncio

- .github/workflows/test.yml
- frame/apps.py
- frame/clients/maximizing_gtk_app.py
- frame/conftest.py
- frame/data/wlr-virtual-pointer-unstable-v1.xml
- frame/display_server.py
- frame/program.py
- frame/protocols/.gitignore
- frame/protocols/__init__.py
- frame/requirements.txt
- frame/test_screencopy_bandwidth.py
- frame/virtual_pointer.py
- frame/virtual_pointer_debug.py
- frame/wayland_client.py
Adds a class that spoofs pointer input with the virtual pointer protocol and a test that demonstrates using it. The test uses a simple GTK app written in Python, since none of the clients we already use have quite the behavior we need.
I've noticed that, weirdly, the screencopy tracker isn't detecting any frames. More investigation is needed.
> Add virtual pointer helper and test

- .github/workflows/test.yml
- frame/conftest.py
- frame/requirements.txt
- frame/test_screencopy_bandwidth.py
Decided to drop the executable and package checks as these will be obvious from test failures anyway.
> tests: move gobject deps to a fixture

- .gitignore
- codecov.yml
- mir-ci/mir_ci/apps.py
- mir-ci/mir_ci/benchmarker.py
- mir-ci/mir_ci/cgroups.py
- mir-ci/mir_ci/clients/drag_and_drop_demo.py
- mir-ci/mir_ci/conftest.py
- mir-ci/mir_ci/display_server.py
- mir-ci/mir_ci/interfaces/benchmarkable.py
- mir-ci/mir_ci/interfaces/benchmarker_backend.py
- mir-ci/mir_ci/program.py
- mir-ci/mir_ci/pytest.ini
- mir-ci/mir_ci/test_apps_can_run.py
- mir-ci/mir_ci/test_drag_and_drop.py
- mir-ci/mir_ci/test_screencopy_bandwidth.py
- mir-ci/mir_ci/test_tests.py
- Provided a new `Benchmarker` class which works with a `cgroups` backend.
- Wrote some tests to make sure that the Benchmarker works
- Integrated the Benchmarker in `test_apps_can_run.py`
1. `git checkout feature/benchmarks`
2. `cd mir-ci/mir-ci`
3 . `pip install -e ..`
4. `pytest --junitxml=junit.xml test_apps_can_run.py`
5. When that finishes, open up `junit.xml` and view the test results
Like this:
```xml
...
<testcase classname="test_apps_can_run.TestAppsCanRun" name="test_app_can_run[mir_demo_server-qterminal]" file="test_apps_can_run.py" line="12" time="3.153">
<properties>
<property name="compositor_cpu_time_microseconds" value="114179"></property>
<property name="compositor_max_mem_bytes" value="58060800"></property>
<property name="compositor_avg_mem_bytes" …
```
> Benchmarking for the DisplayServer and its spawned application

- mir-ci/mir_ci/conftest.py
Without this, qterminal couldn't find fonts on Core.
> mir_ci: apply existing fontconfig

- mir-ci/mir_ci/display_server.py
- mir-ci/mir_ci/output_watcher.py
- mir-ci/mir_ci/test_display_configuration.py
- mir-ci/mir_ci/test_tests.py
- mir-ci/pyproject.toml
- Added a single test for updating the display configuration while a display server is running
- This does not work with ubuntu frame or mir-kiosk as they don't respect the environment variable
- We can add more tests if you think this is a viable route :+1:
> Tests for updating the display configuration while the server is running

- .github/workflows/test.yml
- bin/process_snaps.py
Migrating from MirServer to canonical org, we've identified these as not useful.
> snaps: drop snaps we've identified to be archived

- mir-ci/mir_ci/conftest.py
- mir-ci/pyproject.toml
In newer pytest, the marks "hidden" in the parametrize mark get actioned on. This resulted in calling the `XDG_CONFIG_HOME` mark twice.
Since this is potentially valid (e.g. class-level mark, and then a function-level mark), add support for multiple marks, with the closest ones taking precedence.
> xdg: merge multiple xdg marks

- mir-ci/mir_ci/test_drag_and_drop.py
Slower devices (e.g. Pi3) need longer than the default 10s.
> dnd: extend Robot process timeout

- mir-ci/mir_ci/conftest.py
> deps: bail on error in dependency installation

- mir-ci/mir_ci/robot_libraries/WaylandHid.py
- mir-ci/mir_ci/robot_resources/screencopy.resource
- mir-ci/mir_ci/test_drag_and_drop.py
- mir-ci/mir_ci/virtual_pointer.py
Fixes #83.
Modified keywords:
`Move Pointer To ${destination}`, where `${destination}` can be either the name of an image template, or an xy-point.
`Walk Pointer From ${source} To ${destination}`, where `${source}` and `${destination}` can be the name of image templates, or points.
Examples:
```robot
${p}=    Evaluate    {"x":100, "y":200}
Move Pointer To ${p}
Move Pointer To "template.png"
```
An optional argument, `${proportional}`, can be used to move to a position proportional to the dimensions of the output.
For instance, to move to the center of the output:
```robot
${p}=    Evaluate    {"x":0.5, "y":0.5}
Move Pointer To ${p}    proportional=True
```
or simply
```robot
Move Pointer To ${{{"x":0.5, "y":0.5}}}    proportional=True
```
Examples with `Walk Pointer`:
```robot
Walk …
```
> Add embedded args

- mir-ci/mir_ci/robot_libraries/Screencopy.py
Otherwise a larger screenshots overflows heavily.
> screencopy: give template and screenshot a width

- bin/process_snaps.py
There's no point in it, the only thing this affected was the mir_demo_server staged in the snap, which is not used in automation.
> snaps: drop checkbox-mir-beta

- mir-ci/mir_ci/conftest.py
- mir-ci/mir_ci/fixtures/__init__.py
- mir-ci/mir_ci/fixtures/apps.py
- mir-ci/mir_ci/fixtures/servers.py
- mir-ci/mir_ci/tests/test_apps_can_run.py
- mir-ci/mir_ci/tests/test_display_configuration.py
- mir-ci/mir_ci/tests/test_drag_and_drop.py
- mir-ci/mir_ci/tests/test_screencopy_bandwidth.py
- mir-ci/mir_ci/tests/test_server.py
- mir-ci/mir_ci/tests/test_tests.py
This adds a `ServerCap` flag to describe server capabilities and a `servers(ServerCap)` selector to aid with test parametrization.
> tests: reorganize apps into servers and apps, rework the server fixture and add Miriway

- mir-ci/mir_ci/conftest.py
- mir-ci/mir_ci/fixtures/__init__.py
- mir-ci/mir_ci/fixtures/servers.py
- mir-ci/mir_ci/program/app.py
- mir-ci/mir_ci/program/program.py
- mir-ci/mir_ci/pytest.ini
- mir-ci/mir_ci/tests/test_tests.py
- We can now specify a `MIR_CI_SERVER` and the specified server will be included in our runs
```sh
MIR_CI_SERVER=snap:<SOME_OTHER_MIR_BASED_SHELL>:ALL pytest -k <SOME_OTHER_MIR_BASED_SHELL>
```
> feature: MIR_CI_SERVER environment variable to express external servers

- mir-ci/mir_ci/conftest.py
- mir-ci/mir_ci/tests/test_drag_and_drop.py
- mir-ci/mir_ci/tests/test_osk.py
If absolute, it's only useful when you run one test at a time (like we do with checkbox).
> robot: add `--robot-log` option

- bin/process_snaps.py
> snaps: switch over to `base: core24`

- mir-ci/mir_ci/tests/robot/platforms/wayland/Screencopy.py
`self.frame_count` accessed in `match()` could contain a frame number that is out of sync with the grabbed screenshot. This fix makes sure that the frame count checked in `match()` is the actual frame count when `grab_screenshot()` is called.
> Fix checking against frame_count in Screencopy.match

- mir-ci/mir_ci/wayland/screencopy_tracker.py
You would only see this if you tried to run the `ScreencopyTracker` directly, which I do :)
> bugfix: ScreencopyTracker "with..." to be async
